---
title: "template"
author: "Ruixi Li"
date: "2023-09-19"
output: github_document
---




```{r}
library(tidyverse)
library(readr)
library(readxl)
library(haven)
```

let's import the "._FAS_litters.csv" csv.




```{r}
litters_df <- read.csv("data/data_import_examples/data_import_examples/FAS_litters.csv")

litters_df <- janitor::clean_names(litters_df)
```


Import the same dataset using an absolute path.

```{r}
#litters_df_abs <- read.csv("~/Desktop")#avoid using absolute path,better in your .Rproj directories
```






import "FAS_pups.csv"
```{r}
pups_df <- read.csv("data/data_import_examples/data_import_examples/FAS_pups.csv")

pups_df <- janitor::clean_names(pups_df)
```





```{r}
head(litters_df)
```


```{r, eval=FALSE}
view(litters_df)
```



look at a data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## 'select'

```{r}
select(litters_df,group,litter_number,gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, -starts_with("pups"))

select(litters_df, group, litter_id = litter_number)#rename a column

select(litters_df, group, litter_id = litter_number, everything())

select(litters_df, gd0_weight, everything())
```

'select' vs 'pull'

```{r}
select(litters_df, group)#dataframe in, datafram out
pull(litters_df, group)#dataframe in, list out

```

```{r}
rename(litters_df,litters_id = litter_number)

relocate(litters_df,group, gd0_weight)
```


```{r}
select(pups_df,litter_number,sex,pd_ears)
```



## `filter`
get rid of rows using filter()`
```{r}
filter(litters_df, group =="Con7")

filter(litters_df, !(group =="Mod8"))

filter(litters_df, gd0_weight > 20)

filter(litters_df, group == "Con7" | group == "Con8")

filter(litters_df, group %in% c("Con3","Con7"))

filter(litters_df, group == "Con7" & gd_of_birth == 20)


```

remove rows with missing 
```{r}
drop_na(litters_df, gd0_weight) #will remove rows for which wt_increase is missing.
```


## `mutate`


```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```


## `arrange`

```{r}
view(arrange(litters_df, gd0_weight))

view(arrange(litters_df, group, gd0_weight))
```

## `pipe`

```{r}
litter_df = 
  read_csv("data/data_import_examples/data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-starts_with("pups")) %>%
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight,
  ) %>%
  drop_na(wt_gain) %>%
  arrange(group, wt_gain)
  )
```





```{r}
litter_df =
  read_csv(
    "data/data_import_examples/data_import_examples/FAS_litters.csv",
    skip = 10, 
    na = c("NA",19)
  )
```



```{r, eval=FALSE}
litter_df = 
  read_csv(
    "data/data_import_examples/data_import_examples/FAS_litters.csv",
    col_types = 
      cols(
        Group = col_factor(
        ))
    
```




```{r}
mlb_df = 
  read_excel("data/data_import_examples/data_import_examples/mlb11.xlsx")
mlb_df
```



import a SAS file.


```{r}
pulse_df = read_sas("data/data_import_examples/data_import_examples/public_pulse_data.sas7bdat")
```


# Base R

```{r, eval=FALSE}
litters_df = 
  read.csv("data/data_import_examples/data_import_examples/FAS_litters.csv")
```



```{r}
litters_df_clean <- 
  read_csv("data/data_import_examples/data_import_examples/FAS_litters.csv")

litters_df_cleaned = 
  
  janitor::clean_names(litters_df)



write.csv(litters_df_cleaned)
```

